### ISSUE TITLE
invalid API request with v2.2.2

### ISSUE THREAD

**Issue by vipin5050** [phsmith/rundeck_exporter#10]
I was using old version and that works fine, though with same rundeck token and same URL old version works but not 2.2.2
With 2.2.2 I am getting invalid API request.

2021-02-26 08:47:40,221 - DEBUG - Starting new HTTPS connection (1): abcdef.com:443
2021-02-26 08:47:40,245 - DEBUG - https://abcdef.com:443 "GET /api/24/metrics/metrics HTTP/1.1" 404 None
2021-02-26 08:47:40,247 - CRITICAL - Invalid API Request: /api/24/metrics/metrics

**Comment by phsmith** [comment]
@vipin5050 
What version of Rundeck are you using?

**Comment by vipin5050** [comment]
Its 2.11.5-1

**Comment by phsmith** [comment]
On version 2.2.1 of the exporter I've made a correction in the validation of the API requests, so before that version, you didn't see the error, but it was there.

The /metrics endpoint was introduced on api version 25, so I've just published a new version, 2.2.3, to fix the problem with old version of Rundeck.

**Comment by vipin5050** [comment]
Thanks @phsmith , I am able to run. Let me do few check and will provide feedback
