### ISSUE TITLE
Debug mode is enabled with RUNDECK_EXPORTER_DEBUG: "False"

### ISSUE THREAD

**Issue by doniz** [phsmith/rundeck_exporter#101]
Hi,

I've notice that even tho I do have env variable `RUNDECK_EXPORTER_DEBUG: "False"`, program still generates debug output in the logs.

I've tried also remove double quotes to represent boolean value, however it still failed. 

The only option to disable debugging is to completely remove the env variable.

**Comment by phsmith** [comment]
Thanks for the report @doniz.
I'll take a look and keep you posted.

**Comment by phsmith** [comment]
[v2.8.2](https://github.com/phsmith/rundeck_exporter/releases/tag/v2.8.2) released with proper boolean environment variables validation.

**Comment by doniz** [comment]
Thanks for a quick patch :)

**Comment by doniz** [comment]
I tested and it works. Thanks
