### ISSUE TITLE
[Feature] Document Metrics

### ISSUE THREAD

**Issue by druskus20** [phsmith/rundeck_exporter#12]
I think it would be great to have some documentation on what each metric represents.

**Comment by phsmith** [comment]
Hi @druskus20,

Thanks for the suggestion, I'll work on that.

**Comment by phsmith** [comment]
Just added a basic documentation about the [metrics](../blob/master/docs/METRICS.md)

Unfortunatelly the [Rundeck metrics API documentation](https://docs.rundeck.com/docs/api/rundeck-api.html#metrics-data) is not documented so I'm don't know much about certain metrics exposed.
