### ISSUE TITLE
can not get status of running job

### ISSUE THREAD

**Issue by vipin5050** [phsmith/rundeck_exporter#14]
Not sure if there is any technical reason not to get status of running jobs. I am able to get status of failed jobs , successful jobs but for all running jobs its always get status "0"

It would be good if we can get the status as 1 if the job is running.

let me know if you need more information.

**Comment by phsmith** [comment]
Just released the version 2.2.6 that fix the problem.
Rundeck has a different endpoint to get the running job status.

**Comment by vipin5050** [comment]
you can close this issue, validated.
