### ISSUE TITLE
grafana dashboard issue

### ISSUE THREAD

**Issue by vipin5050** [phsmith/rundeck_exporter#15]
Not sure if this issue is related to grafana dashboard or there is something in exporter. Issue what I am seeing after created dashoard in grafana its little misleading. I am plotting execution status of all the jobs to see if there are any jobs in rundeck which are overlapping. I get the status of overlapping jobs but the dashboard shows once the job is finished.

<img width="866" alt="Screen Shot 2021-03-30 at 1 22 50 PM" src="https://user-images.githubusercontent.com/79691636/113052529-1d541300-915c-11eb-93ca-b7c5200854fa.png">

through duration of the job it shows ok which is around 3 hours.

**Comment by vipin5050** [comment]
yes in legend it collect right start time but in grafana X axis it shows when the metrics was collected and dont know how to workaround it :-(

**Comment by phsmith** [comment]
Think that if you don't show X-axis or change the mode to Series, like bellow, makes It better.

![image](https://user-images.githubusercontent.com/8090930/113292029-48f50b80-92ca-11eb-9357-5bc236e5560d.png)

**Comment by vipin5050** [comment]
looks good, I was able to put grant chart in grafana and it looks what I was looking, basically it gives me picture of jobs if they are overlapping and start and end time.
<img width="920" alt="Screen Shot 2021-04-13 at 9 25 29 AM" src="https://user-images.githubusercontent.com/79691636/114587191-45527480-9c3a-11eb-84db-093005377756.png">

**Comment by vipin5050** [comment]
Thanks, you can close this issue
