### ISSUE TITLE
Need to have memory stats 

### ISSUE THREAD

**Issue by vipin5050** [phsmith/rundeck_exporter#16]
it would be nice to have memory stats as I see some times rundeck container or system runs out of memory and there is no way to find out what was the stat . you can get current stats from rundeck UI but not from exporter

<img width="296" alt="Screen Shot 2021-04-13 at 9 30 03 AM" src="https://user-images.githubusercontent.com/79691636/114587809-d9244080-9c3a-11eb-957e-e25e7c4ea12e.png">

but in exporter there is no indication 

`python_gc_objects_collected_total{generation="0"} 232.0
python_gc_objects_collected_total{generation="1"} 2250.0
python_gc_objects_collected_total{generation="2"} 29712.0
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
python_gc_collections_total{generation="0"} 11913.0
python_gc_collections_total{generation="1"} 1083.0
python_gc_collections_total{generation="2"} 97.0
python_info{implementation="CPython",major="3",minor="7",patchlevel="9",version="3.7.9"} 1.0
process_virtual_memory_bytes 3.57736448e+09
process_resident_memory_bytes 4.17480704e+08
process_start_time_seconds 1.61720609141e+09
process_cpu_seconds_total 2900.8199999999997
process_open_fds 381.0
process_max_fds 1024.0`

**Comment by vipin5050** [comment]
I see it was there in 2.0.0, not sure why it was removed, you can make it optional and let user choose if they want or not.

**Comment by phsmith** [comment]
On early versions, the rundeck_exporter wasn't part of the oficial Prometheus page, so I had to make many fixes proposed by the Prometheus curators and one o then was remove data about system info. As they suggested, if you need system info, you need to use the node_exporter.

**Comment by vipin5050** [comment]
but the issue with node exporter is it does not get JVM stats for rundeck container and there is no way you can install node exporter in container where JVM stats for rundeck container is very specific to rundeck only. So I dont think node exporter is a solution.

**Comment by phsmith** [comment]
I did understand your point!
Think that I can put options to show the cpu and memory stats.

**Comment by vipin5050** [comment]
Thanks, and also when you are going to build new version with the fix then can you add --version option to check which version of exporter you are running. Since I have multiple version on my system and getting lost which one is which. ;-)
I guess I can rename but it would be nice i can do some thing like

#rundeck_exporter --version

and it prints github location and release number or at least release number.

**Comment by phsmith** [comment]
@vipin5050 
New version has the following new options: --rundeck.cpu.stats, --rundeck.memory.stats and --version

**Comment by vipin5050** [comment]
Thanks :-)
