### ISSUE TITLE
Alert for more than X failing jobs

### ISSUE THREAD

**Issue by rdoering** [phsmith/rundeck_exporter#22]
Hi

I try to set up an alert for more than X failing executions in last hour for project Y.

Failing execution can be shown by `rundeck_project_execution_status{status='failed'}  > 0`. It can also be grouped by `group by (project_name) (rundeck_project_execution_status{status='failed'}  > 0)`.

But how to do that with with an vector value? I guess I have to use `increase` but I am not sure how?

**Comment by phsmith** [comment]
Hi @rdoering!

I think that you can do something like:

```
sum(count_over_time(rundeck_project_execution_status{project_name="project_y", status="failed"}[1h])) by (project_name)
```
