### ISSUE TITLE
rundeck_scheduler_quartz_scheduledJobs not showing up

### ISSUE THREAD

**Issue by vipin5050** [phsmith/rundeck_exporter#27]
I have have been using 2.4
./rundeck_exporter.py --version
rundeck_exporter 2.4.0

though I dont see exporter is pulling any rundeck_scheduler_quartz_scheduledJobs metrics, is depending on rundeck version as I am running quite old version.

**Comment by phsmith** [comment]
Hello @vipin5050!
Probably the Rundeck version that you're using doesn't exposes the `scheduler.quartz.scheduledJobs`.
You could check that through `https://your_rundeck_address/metrics`

**Comment by vipin5050** [comment]
Hi @phsmith 
I can see at https://your_rundeck_address/metrics

    "rundeck.scheduler.quartz.scheduledJobs" : {
      "count" : 21
    }

but not at the prometheus, I checked on localhost also .e.g
curl http://localhost:xxxx/metrics where exporter is running but no rundeck_scheduler_quartz_scheduledJobs metrics shows up

**Comment by phsmith** [comment]
@vipin5050,

The problem is that the endpoint that returns the metrics like `rundeck.scheduler.quartz.scheduledJobs` was only introduced from Rundeck API version 25+ (<https://docs.rundeck.com/docs/api/rundeck-api-versions.html#api-changes>).

If you check rundeck_exporter logs you could see a message like that: 

> 2022-02-22 01:49:21,198 - WARNING - Unsupported API version "24" for API request: /api/24/metrics/metrics. Minimum supported version is 25

You can also check what the latest API version that your Rundeck instance is using by checking the `rundeck_system_info` metric:

> rundeck_system_info{apiversion="40",base="/home/rundeck",build="3.4.8-20211214",buildGit="v3.4.8-0-g62288dc",node="e95f20a5cf9b",serverUUID="a14bc3e6-75e8-4fe4-a90d-a16dcc976bf6",version="3.4.8-20211214"} 1.0

**Comment by vipin5050** [comment]
you might be right though I have rundeck with api version 24 and when I collect metrics, it has rundeck.scheduler.quartz.scheduledJobs metrics also

<img width="827" alt="Screen Shot 2022-02-24 at 12 48 33 AM" src="https://user-images.githubusercontent.com/79691636/155490615-9d2272bc-695b-4e91-bbd4-2a0a693e92fd.png">

`{
  "version" : "3.0.0",
  "gauges" : {
    "dataSource.connection.pingTime" : {
      "value" : 4
    },
    "rundeck.scheduler.quartz.runningExecutions" : {
      "value" : 2
    },
    "rundeck.services.AuthorizationService.sourceCache.evictionCount" : {
      "value" : 0
    },
    "rundeck.services.AuthorizationService.sourceCache.hitCount" : {
      "value" : 53484954
    },
    "rundeck.services.AuthorizationService.sourceCache.hitRate" : {
      "value" : 0.999999700850538
    },
    "rundeck.services.AuthorizationService.sourceCache.loadExceptionCount" : {
      "value" : 0
    },
    "rundeck.services.AuthorizationService.sourceCache.missCount" : {
      "value" : 16
    },
    "rundeck.services.NodeService.nodeCache.evictionCount" : {
      "value" : 0
    },
    "rundeck.services.NodeService.nodeCache.hitCount" : {
      "value" : 59536
    },
    "rundeck.services.NodeService.nodeCache.hitRate" : {
      "value" : 0.99983206260706
    },
    "rundeck.services.NodeService.nodeCache.loadExceptionCount" : {
      "value" : 0
    },
    "rundeck.services.NodeService.nodeCache.missCount" : {
      "value" : 10
    },
    "rundeck.services.ProjectManagerService.fileCache.evictionCount" : {
      "value" : 0
    },
    "rundeck.services.ProjectManagerService.fileCache.hitCount" : {
      "value" : 36296
    },
    "rundeck.services.ProjectManagerService.fileCache.hitRate" : {
      "value" : 0.9992291597841647
    },
    "rundeck.services.ProjectManagerService.fileCache.loadExceptionCount" : {
      "value" : 0
    },
    "rundeck.services.ProjectManagerService.fileCache.missCount" : {
      "value" : 28
    },
    "rundeck.services.ProjectManagerService.projectCache.evictionCount" : {
      "value" : 15933
    },
    "rundeck.services.ProjectManagerService.projectCache.hitCount" : {
      "value" : 10742171
    },
    "rundeck.services.ProjectManagerService.projectCache.hitRate" : {
      "value" : 0.9970377997725283
    },
    "rundeck.services.ProjectManagerService.projectCache.loadExceptionCount" : {
      "value" : 0
    },
    "rundeck.services.ProjectManagerService.projectCache.missCount" : {
      "value" : 31915
    },
    "rundeck.services.ProjectManagerService.sourceCache.evictionCount" : {
      "value" : 0
    },
    "rundeck.services.ProjectManagerService.sourceCache.hitCount" : {
      "value" : 33684418
    },
    "rundeck.services.ProjectManagerService.sourceCache.hitRate" : {
      "value" : 0.9999987531342346
    },
    "rundeck.services.ProjectManagerService.sourceCache.loadExceptionCount" : {
      "value" : 0
    },
    "rundeck.services.ProjectManagerService.sourceCache.missCount" : {
      "value" : 42
    }
  },
  "counters" : {
    "com.codahale.metrics.servlet.AbstractInstrumentedFilter.activeRequests" : {
      "count" : 1
    },
    "rundeck.scheduler.quartz.scheduledJobs" : {
      "count" : 28
    }
  },`

But when I get the metrics from exporter it does not have rundeck.scheduler.quartz.scheduledJobs

**Comment by phsmith** [comment]
Rundeck shows the following error when trying to request the endpoint `/api/24/metrics/metrics`:
```
curl -ks -H 'X-Rundeck-Auth-Token: XXXXXXXXXXXXXXXXX' http://localhost:4440/api/24/metrics/metrics | jq .
```
```json
{
  "error": true,
  "apiversion": 40,
  "errorCode": "api.error.api-version.unsupported",
  "message": "Unsupported API Version \"24\". API Request: /api/24/metrics/metrics. Reason: Minimum supported version: 25"
}
``` 

But I implemented a way to retrieve the data without consuming the API, but to archive that you need to pass a user and password that has permissions in `http://rundeck_url/metrics/metrics`

```
export RUNDECK_TOKEN=xxxxxxxx \
       RUNDECK_USERPASSWORD=yyyyyyy

./rundeck_exporter.py --rundeck.url http://localhost:4440 \
                      --rundeck.username=admin \
                      --rundeck.api.version=24 \
                      --rundeck.projects.executions
```
