### ISSUE TITLE
Is it possible to have average running time with job status

### ISSUE THREAD

**Issue by vipin5050** [phsmith/rundeck_exporter#39]
I have created dashboard in grafana to show job status for failed, success etc. I was thinking it would be good if I can get average execution time for the jobs also. You can get the average execution time in rundeck console as shown
<img width="505" alt="Screen Shot 2022-04-09 at 9 59 09 AM" src="https://user-images.githubusercontent.com/79691636/162584305-17f01c60-0bee-400d-af88-eb6934470ab8.png">

**Comment by phsmith** [comment]
@vipin5050 you can do that using the `rundeck_project_execution_duration_seconds` metrics.

See the example below:

Query: `topk(20, sum(rundeck_project_execution_duration_seconds > 20000) by (project_name, job_name))`

![Screenshot_2022-04-09_15-04-09](https://user-images.githubusercontent.com/8090930/162586226-a7e79a61-69ea-4fdb-b3fe-b977fed04862.png)

**Comment by vipin5050** [comment]
Thanks @phsmith for quick update, its close enough though what I am looking is in my dashboard I have table and somehow if I can get the average past running time of the job then I will know if my running job is delayed or on time or what is expected finish time ( like if flight is on time or delayed)
<img width="1424" alt="Screen Shot 2022-04-09 at 11 43 54 AM" src="https://user-images.githubusercontent.com/79691636/162587829-d713464d-c2dd-4cd6-91cb-c0279218de8a.png">

I dont get current status of the running job until it finishes

**Comment by phsmith** [comment]
Humm, understood your point now.
Need to check, but I think that you can work with `avg_over_time` Prometheus function to work around that.
Example: `avg_over_time(rundeck_project_execution_duration_seconds[$__range])`

**Comment by vipin5050** [comment]
avg_over_time works only if the job is not running if I try to get avg_over_time for the job which are running state then for those job I get -ve average so some how I have to exclude job which are not in running state and then get the average. But then if job is in running state I dont know whats the average time :-(

**Comment by phsmith** [comment]
I think that you can try something like this:
```
avg(max_over_time(rundeck_project_execution_duration_seconds[$__range]) > 0) by (project_name, job_name)
```

**Comment by phsmith** [comment]
Closing this issue. If the problem was not solved, feel free to re-open it.
