### ISSUE TITLE
Running jobs cause rundeck_project_execution_duration_seconds to report negative values

### ISSUE THREAD

**Issue by trayo** [phsmith/rundeck_exporter#40]
Because running executions are combined with past executions
https://github.com/phsmith/rundeck_exporter/blob/7e1c54d59211fffbd1e98ebb1f530ebbfdbc76c3/rundeck_exporter.py#L224-L225

when the `end_time` is grabbed later, it won't exist in the Rundeck API call so it will be set to `0`
https://github.com/phsmith/rundeck_exporter/blob/7e1c54d59211fffbd1e98ebb1f530ebbfdbc76c3/rundeck_exporter.py#L270-L271

and the resulting calculation for duration
https://github.com/phsmith/rundeck_exporter/blob/7e1c54d59211fffbd1e98ebb1f530ebbfdbc76c3/rundeck_exporter.py#L272

will result in a negative number.

According to the [Rundeck API documentation](https://docs.rundeck.com/docs/api/rundeck-api.html#listing-running-executions) both the `GET /api/14/project/[PROJECT]/executions` endpoint and `GET /api/14/project/[PROJECT]/executions/running` endpoint use the same response which contains

```json
"job": {
  "averageDuration": 6094,
},
```

I think replacing the calculation with the `averageDuration` would lead to better data accuracy.

**Comment by phsmith** [comment]
You're partially right about `job_execution_duration`...
I've just checked that Rundeck API only retrieves the `end-time` and `averageDuration` when a job was finished successfully.

Previous `succeeded` job running:
```json
{
    "id": 11968,
    "href": "http://localhost:4440/api/40/execution/11968",
    "permalink": "http://localhost:4440/project/Test/execution/show/11968",
    "status": "running",
    "project": "Test",
    "executionType": "scheduled",
    "user": "admin",
    "date-started": {
        "unixtime": 1650487500011,
        "date": "2022-04-20T20:45:00Z"
    },
    "job": {
        "id": "fff6e7b1-4fdd-467b-b807-e168f9ee8865",
        "averageDuration": 15335,
        "name": "Success after 15s",
        "group": "",
        "project": "Test",
        "description": "",
        "href": "http://localhost:4440/api/40/job/fff6e7b1-4fdd-467b-b807-e168f9ee8865",
        "permalink": "http://localhost:4440/project/Test/job/show/fff6e7b1-4fdd-467b-b807-e168f9ee8865"
    },
    "description": "sleep 15 && echo \"Succeeded after 15s\"",
    "argstring": null,
    "serverUUID": "a14bc3e6-75e8-4fe4-a90d-a16dcc976bf6"
},
```

Previous `failed` job running:
```json
{
    "id": 11969,
    "href": "http://localhost:4440/api/40/execution/11969",
    "permalink": "http://localhost:4440/project/Test/execution/show/11969",
    "status": "running",
    "project": "Test",
    "executionType": "scheduled",
    "user": "admin",
    "date-started": {
        "unixtime": 1650487500011,
        "date": "2022-04-20T20:45:00Z"
    },
    "job": {
        "id": "e4a5400d-117b-4b76-9f8c-8e8a0eca76e8",
        "name": "Fail after 15s",
        "group": "",
        "project": "Test",
        "description": "",
        "href": "http://localhost:4440/api/40/job/e4a5400d-117b-4b76-9f8c-8e8a0eca76e8",
        "permalink": "http://localhost:4440/project/Test/job/show/e4a5400d-117b-4b76-9f8c-8e8a0eca76e8"
    },
    "description": "sleep 15 && echo \"Failed after 15s\" && exit 1",
    "argstring": null,
    "serverUUID": "a14bc3e6-75e8-4fe4-a90d-a16dcc976bf6"
}
```

So, I think that I can manage in the code the `end-time` of the job based on his status and the calculate the `job_execution_duration`, the problem is that it probably won't be precise.

Other way that could work is using the following query:
```
avg(max_over_time(rundeck_project_execution_duration_seconds[$__range]) > 0) by (project_name, job_name)
```

**Comment by trayo** [comment]
You could use `job_info.get('averageDuration', 0)` to account for jobs that have never had a successful execution.

**Comment by phsmith** [comment]
Yeah, you're right, that way will be nice.

**Comment by phsmith** [comment]
New version published!
