### ISSUE TITLE
Project metrics have duplicate HELP headers. 

### ISSUE THREAD

**Issue by WilsonSunBritten** [phsmith/rundeck_exporter#42]
Typically for the same metric the proper format is to only display it's header once, currently in this project it is displayed multiple times. 

Example -- in this case the expected output would only have the line 
# HELP rundeck_project_execution_status Rundeck Project test-project Execution Status
once. I believe this is because the re-instantialization of the MetricGaugeFamily for each project like start_metrics. Hope to follow up with my own submission soon.

# HELP rundeck_project_execution_status Rundeck Project test-project Execution Status
# TYPE rundeck_project_execution_status gauge
rundeck_project_execution_status{execution_id="654",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="7c0247e6-3fbb-4c20-913c-331a1a7c3959",job_name="testjob-1",project_name="test-project",status="succeeded",user="admin"} 1.0
rundeck_project_execution_status{execution_id="654",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="7c0247e6-3fbb-4c20-913c-331a1a7c3959",job_name="testjob-1",project_name="test-project",status="running",user="admin"} 0.0
rundeck_project_execution_status{execution_id="654",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="7c0247e6-3fbb-4c20-913c-331a1a7c3959",job_name="testjob-1",project_name="test-project",status="failed",user="admin"} 0.0
rundeck_project_execution_status{execution_id="654",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="7c0247e6-3fbb-4c20-913c-331a1a7c3959",job_name="testjob-1",project_name="test-project",status="aborted",user="admin"} 0.0
rundeck_project_execution_status{execution_id="654",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="7c0247e6-3fbb-4c20-913c-331a1a7c3959",job_name="testjob-1",project_name="test-project",status="unknown",user="admin"} 0.0
# HELP rundeck_project_start_timestamp Rundeck Project test-project Start Timestamp
# TYPE rundeck_project_start_timestamp gauge
rundeck_project_start_timestamp{execution_id="644",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="dcf0d988-74b6-47ec-b2b8-ba59866c7cdc",job_name="testjob-2",project_name="test-project",user="admin"} 1.65211446002e+012
# HELP rundeck_project_execution_duration_seconds Rundeck Project test-project Execution Duration
# TYPE rundeck_project_execution_duration_seconds gauge
rundeck_project_execution_duration_seconds{execution_id="644",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="dcf0d988-74b6-47ec-b2b8-ba59866c7cdc",job_name="testjob-2",project_name="test-project",user="admin"} 661.0
# HELP rundeck_project_execution_status Rundeck Project test-project Execution Status
# TYPE rundeck_project_execution_status gauge
rundeck_project_execution_status{execution_id="644",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="dcf0d988-74b6-47ec-b2b8-ba59866c7cdc",job_name="testjob-2",project_name="test-project",status="succeeded",user="admin"} 1.0
rundeck_project_execution_status{execution_id="644",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="dcf0d988-74b6-47ec-b2b8-ba59866c7cdc",job_name="testjob-2",project_name="test-project",status="running",user="admin"} 0.0
rundeck_project_execution_status{execution_id="644",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="dcf0d988-74b6-47ec-b2b8-ba59866c7cdc",job_name="testjob-2",project_name="test-project",status="failed",user="admin"} 0.0
rundeck_project_execution_status{execution_id="644",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="dcf0d988-74b6-47ec-b2b8-ba59866c7cdc",job_name="testjob-2",project_name="test-project",status="aborted",user="admin"} 0.0
rundeck_project_execution_status{execution_id="644",execution_type="scheduled",instance_address="rundeck3:4440",job_group="",job_id="dcf0d988-74b6-47ec-b2b8-ba59866c7cdc",job_name="testjob-2",project_name="test-project",status="unknown",user="admin"} 0.0

**Comment by WilsonSunBritten** [comment]
Pardon formatting, should have realized the impact of pound symbols.

**Comment by phsmith** [comment]
Published release [v2.4.9](https://github.com/phsmith/rundeck_exporter/releases/tag/v2.4.9)!
