### ISSUE TITLE
Connection Reset by Peer

### ISSUE THREAD

**Issue by tech-dad** [phsmith/rundeck_exporter#52]
Greetings,

I am relatively new to this and I am currently encountering an issue after the exporter is started. Have you seen this behavior before?

`Exception happened during processing of request from ('172.16.54.132', 59344)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/wsgiref/simple_server.py", line 118, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer`

Server Information:

`[exporter@rundeck05 sbin]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)`

`[exporter@rundeck05 sbin]$ python3 --version
Python 3.6.8`

`[exporter@rundeck05 sbin]$ pip3 list
cachetools (4.2.4)
certifi (2021.10.8)
charset-normalizer (2.0.12)
idna (3.3)
pip (9.0.3)
prometheus-client (0.14.1)
requests (2.27.1)
setuptools (39.2.0)
urllib3 (1.26.9)`

**Comment by phsmith** [comment]
Hi @tech-dad!

Didn't get this problem before, but I'm suspecting that it might be a problem with python version... I only tested the exporter with python 3.7+.

Can you update python to a newer version? Or, can you run Docker or Podman in your server and try to run the [rundeck_exporter container](https://github.com/phsmith/rundeck_exporter#running-with-docker)?

**Comment by tech-dad** [comment]
I think that is exactly the issue. I was installing python3 from:

https://github.com/darkwizard242/ansible-role-python3

I can confirm that is working locally with version >=3.7

**Comment by phsmith** [comment]
Great! 
Lemme know if I can help with anything else.
