### ISSUE TITLE
error: unrecognized arguments

### ISSUE THREAD

**Issue by licsuj27** [phsmith/rundeck_exporter#53]
./rundeck_exporter.py RUNDECK_USERPASSWORD "xxxx"
rundeck_exporter.py: error: unrecognized arguments: RUNDECK_USERPASSWORD:

 ./rundeck_exporter.py --rundeck.userpassword "xxxxx"
rundeck_exporter.py: error: unrecognized arguments: --rundeck.userpassword

Am i doing something wrong? tried with colon, with equals and some output

**Comment by phsmith** [comment]
@licsuj27,

To pass the `RUNDECK_USERPASSWORD` to rundeck_exporter, you need to export the var or pass it before the exporter script, for example:

```
export RUNDECK_USERNAME=admin \ 
           RUNDECK_PASSWORD=admin

./rundeck_exporter --rundeck.url 'http://localhost:4440'
```

You can also do:
```
RUNDECK_USERNAME=admin RUNDECK_PASSWORD=admin ./rundeck_exporter --rundeck.url 'http://localhost:4440'
```
