### ISSUE TITLE
Error while retrieving System Info

### ISSUE THREAD

**Issue by Qmeriaux** [phsmith/rundeck_exporter#61]
I tried to execute the python script with env var set in a bash script.
There was no problem running the script and defining env, but I encountered an error when the python script tried to reach the '/system/info' API endpoint.
It seems that the script doesn't receive a correct JSON response (see screenshot linked), but when I try to reach the endpoint with a curl, I get a well-formatted JSON response.

![Sans titre](https://user-images.githubusercontent.com/35970288/210247536-8ca6c1f9-08c8-4a3c-a723-65bcca8b9bd2.png)

I thought it was due to the 'Accept' header, but it seems that the header is already in the python script (line 202), so the response should be in JSON.

What can I do to fix this ?
Thank you

**Comment by phsmith** [comment]
Hey @Qmeriaux, I've just tested it by passing the environment variables to the rundeck_exporter.py and everything worked great as you can see in the screnshot below. 

Are you using python 3.7+?

![Screenshot_20230102_132743](https://user-images.githubusercontent.com/8090930/210257902-c36c1b9e-0e6b-4a66-911d-3d003011343b.png)

**Comment by Qmeriaux** [comment]
Hey ! I was on Python 3.6.8 when I first posted the issue, so I just upgraded to Python 3.8.13, but still get the same error.

**Comment by phsmith** [comment]
> EDIT : it was a proxy issue, it's now working fine ! Thank you for your time !
Oh, I see. No problem! 
Feel free to reach me out if you find any problem.
