### ISSUE TITLE
Wrong execution count for a time period

### ISSUE THREAD

**Issue by bcruvelier** [phsmith/rundeck_exporter#63]
Hello !

We’ve just deployed the exporter on our Rundeck and we have an issue when we try to set up an alert. 

We want to raise an alert when a given job (scheduled to be triggered once an hour) fails more than 2 times in the last 3 hours. 

We thought we had the right query with that (taken from [this issue](https://github.com/phsmith/rundeck_exporter/issues/62#issuecomment-1412853051)) : 
```
sum by (job_name) (max_over_time(rundeck_project_execution_status{job_name="[HIDDEN] Test Rundeck Nodes",status="failed"}[3h])) >= 2
```
But the alert is still up even when the 2 jobs failed more than 6 hours ago : 
![image](https://user-images.githubusercontent.com/37801065/228240840-910fa4cd-53ae-4565-ba8f-8eb419370c3d.png)

The issue is more obvious when we try to get the number of executions (whatever the status is) in the last 3 hours with this query : 
```
sum by (job_name) (max_over_time(rundeck_project_execution_status{job_name="[HIDDEN] Test Rundeck Nodes"}[3h]))
```
![image](https://user-images.githubusercontent.com/37801065/228240971-18e8be7a-82f1-40d9-a0cf-f23b7677dddc.png)
We get a total of 17 when it should be 3. 
Here is the screenshot take from Rundeck activity tab of the job : 
![image](https://user-images.githubusercontent.com/37801065/228241358-84ede35b-d514-47cf-96dd-bd9b5a68ddbb.png)

We don’t know how to solve this problem, can you help us ?

**Comment by phsmith** [comment]
Hey @bcruvelier!
I got it, but I wasn't able to replicate this behavior. See in the images:

For longer period, I got 5 failed executions in Rundeck and also in Prometheus
![Screenshot_20230329_190009](https://user-images.githubusercontent.com/8090930/228678573-3a8e6427-883f-4461-818d-78ad6fe25de8.png)

![Screenshot_20230329_190017](https://user-images.githubusercontent.com/8090930/228678584-05947ba9-de24-437f-a341-d36d4eaffd51.png)

For little bit shorter period, I got 2 failed executions only on both Rundeck and Prometheus:

![Screenshot_20230329_185846](https://user-images.githubusercontent.com/8090930/228679176-842c3879-9dc3-4eff-b2bc-0d0b43d66e05.png)

![Screenshot_20230329_185905](https://user-images.githubusercontent.com/8090930/228679188-e832798f-1127-4cff-8c92-9508a34d320d.png)

**Comment by bcruvelier** [comment]
Thanks for your quick response. 

Do you have suggestions on how I can debug it ?

I'm out of ideas at this point.

**Comment by phsmith** [comment]
`increase` seems to be a good option in your case. It returns the value that way because the way it calculates the metrics in the interval.

If you want to get a integer value you can use `floor()` function like this:
```
floor(sum(increase(rundeck_project_execution_status{job_name="[HIDDEN] Test Rundeck Nodes"}[3h])) by (project_name, job_name))
```

**Comment by phsmith** [comment]
Hey @bcruvelier , I'm closing the issue, but you can reopen it if the problem wasn't solved. :+1:
