### ISSUE TITLE
Question about recentFiler=1d for getting executions

### ISSUE THREAD

**Issue by davidcpell** [phsmith/rundeck_exporter#68]
Hi @phsmith, I'm integrating `rundeck_exporter` (thanks for this!) and while looking at the code came across the use of 1d as a `recentFilter` when getting executions:

https://github.com/phsmith/rundeck_exporter/blob/82b203ab642593bb59340ef2bbd8fc8b9a6522e7/rundeck_exporter.py#L232-L233

Can you explain the reasoning behind this value? I just want to make sure things will work as expected when Prometheus is scraping every minute. Will I be duplicating metrics?

**Comment by phsmith** [comment]
Hey @davidcpell!
Yeah, let me explain.

That point in the code retrieves the 20 _(max => project_executions_limit = > 20 by default)_ most recent `project executions` during the day, or in the last 24h.

For example, the `rundeck_project_execution_status` metric shows 5 metrics every time the exporter is scraped, each one representing the status of the rundeck jobs, and `value` is set to `1` for the current status and `0` for the others. Every minute you can see these metrics,  so yeah, you can get the same metrics values over a period of time, but it's purely for having more accurate results.

Don't know if I was clear enough, lemme know if not.

**Comment by davidpellcb** [comment]
I'm still struggling to see how this works out in a case where we are scraping every minute but the exporter is looking back 24h for executions. For example, if there were 10 executions of a certain job in the last 24h and Prometheus is scraping every minute, would we not be adding 10 to the counter every time a scrape takes place even if no more executions are happening (until 24h have gone by and the API query no longer finds those 10 executions)?

**Comment by davidcpell** [comment]
I'm still struggling to see how this works out in a case where we are scraping every minute but the exporter is looking back 24h for executions. For example, if there were 10 executions of a certain job in the last 24h and Prometheus is scraping every minute, would we not be adding 10 to the counter every time a scrape takes place even if no more executions are happening (until 24h have gone by and the API query no longer finds those 10 executions)?

Or a gauge example: let's say we had 100 executions evenly spread out over the course of 24h, and the next day there are 0 executions the whole day. At noon the next day (halfway through the day) wouldn't we still be sending a value of 50 to Prometheus? And it would look like the value went from 100 to 50 when actually there are 0 executions for those times on the 2nd day?

Sorry if I'm misunderstanding something either in the exporter or Prom itself!

**Comment by phsmith** [comment]
@davidcpell You're absolutely right!
I've just made a few changes. I added the parameter `--rundeck.projects.executions.filter`, default to `5n` (5 minutes), so you can now change the behavior of the query.
What do you think?
