### ISSUE TITLE
 KeyError: 'system'

### ISSUE THREAD

**Issue by barra51** [phsmith/rundeck_exporter#7]
Hi,

Starting the docker image trough docker-compose, trigger the following set of errors:

`
stats_1       | Traceback (most recent call last):
stats_1       |   File "/usr/bin/rundeck_exporter.py", line 367, in <module>
stats_1       |     RundeckMetricsCollector.run()
stats_1       |   File "/usr/bin/rundeck_exporter.py", line 354, in run
stats_1       |     REGISTRY.register(RundeckMetricsCollector())
stats_1       |   File "/usr/local/lib/python3.9/site-packages/prometheus_client/registry.py", line 26, in register
stats_1       |     names = self._get_names(collector)
stats_1       |   File "/usr/local/lib/python3.9/site-packages/prometheus_client/registry.py", line 66, in _get_names
stats_1       |     for metric in desc_func():
stats_1       |   File "/usr/bin/rundeck_exporter.py", line 309, in collect
stats_1       |     rundeck_system_info.add_metric([], {x: str(y) for x, y in system_info['system']['rundeck'].items()})
stats_1       | KeyError: 'system'
`
Probably the prometheus package needs to be updated?

best,
Miguel

**Comment by phsmith** [comment]
Hi @barra51 

What's the version of Rundeck are you running?

**Comment by barra51** [comment]
Thanks for your response @phsmith !!
I'm working with rundeck version 3.3.5

**Comment by barra51** [comment]
Hi again @phsmith 

After some research in my rundeck server under service.log, I saw a lot of denied access API calls. I recreated the API token, everything is working as expected now. Not sure why of this, previous token still had 8 days of life.

Thank you so much, I'm closing this.

**Comment by phsmith** [comment]
Nice @barra51 
I'll try to make that type of error more clear.
Thanks!
