### ISSUE TITLE
systemd service doesn't work according to docu

### ISSUE THREAD

**Issue by iklema** [phsmith/rundeck_exporter#77]
Hello,

I'd like to report that systemd service for rundeck_exporter doesn't work according to docu because of missing VERSION file in the rundeck_exporter path.

**Getting following error:**
# /usr/local/bin/rundeck_exporter --help
Traceback (most recent call last):
  File "/usr/local/bin/rundeck_exporter", line 30, in <module>
    __version__ = open(path.join(path.dirname(__file__),'VERSION')).read()
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/VERSION'

When i moved VERSION file with script to new path all works fine.
Please update script with version or documentation of systemd service.

Thank you!

**Comment by phsmith** [comment]
Hello @iklema,

Thanks for your report.
I have just released a new version that fixes that problem.

**Comment by phsmith** [comment]
I'm closing this issue, but you can reopen it if the problem hasn't been solved.
