### ISSUE TITLE
Possible to give example of setting this exporter in systemd?

### ISSUE THREAD

**Issue by hongyuhy** [phsmith/rundeck_exporter#9]
Hi, 

I am thinking of using this exporter like how node-exporter is used. For example: https://github.com/prometheus/node_exporter/blob/master/examples/systemd/node_exporter.service

Is it possible for rundeck_exporter to have similar functionality?

**Comment by phsmith** [comment]
Hi @hongyuhy!

For sure it's possible to make a systemd service with rundeck_exporter too.

I'll publish a model like that from the node_exporter in the project.

**Comment by hongyuhy** [comment]
Hi @phsmith ,

Thanks! looking forward for the example.

**Comment by phsmith** [comment]
@hongyuhy ,

I've just commit the example of systemd unit file for rundeck_exporter: https://github.com/phsmith/rundeck_exporter/tree/master/examples/systemd

**Comment by hongyuhy** [comment]
Alright thanks for the example @phsmith , very much appreciated.
