### ISSUE TITLE
Request - Metrics - Node Active/Passive

### ISSUE THREAD

**Issue by Zwordi** [phsmith/rundeck_exporter#97]
Hello there :).

It would be helpful to have a metric boolean type to see if the rundeck instance is active or passive.

Thanks,

**Comment by phsmith** [comment]
Hey, I'm going to take a look at your request.

**Comment by Zwordi** [comment]
Great Thank you.

**Comment by phsmith** [comment]
@Zwordi, I just released version 2.8.0 of the exporter with the new metrics `rundeck_execution_mode_active` and `rundeck_execution_mode_passive`.

**Comment by doniz** [comment]
Any reasons why it cannot be under one option `rundeck_execution_mode`and 1 would represent active, 0 - passive ?

**Comment by phsmith** [comment]
Hi @doniz, it's just a good practice to define clear metric names for easier understanding of their purpose.
