### ISSUE TITLE
 Attribute Error: None Type Get()

### ISSUE THREAD

**Issue by mbaleey** [phsmith/rundeck_exporter#98]
Hello,

Getting this error right after status 200 against self.request('/system/info')..

Attribute Error: None Type Get() 

Seeing references to this line here as seen in screenshot.

https://github.com/phsmith/rundeck_exporter/blob/75dbdcfe33856cd021532a6d73a0bc9d559a50bd/rundeck_exporter.py#L448

I have a feeling this might be a quick fix on my part and something simple I'm overlooking?

Any ideas why I keep getting hit on this error?  Using api v40 and exporter 2.71 rev.
![20240822_170011](https://github.com/user-attachments/assets/351e8308-5ee5-4597-9c25-f985cd507c3f)

Thank you,[

**Comment by phsmith** [comment]
Hi there,

I suspect it's because the user or token you're using doesn't have permission to read `system` attributes.
Could you take a look at the following instructions and see if that helps?
https://github.com/phsmith/rundeck_exporter?tab=readme-ov-file#api-authentication

**Comment by mbaleey** [comment]
> Hi there,
> 
> I suspect it's because the user or token you're using doesn't have permission to read `system` attributes. Could you take a look at the following instructions and see if that helps? https://github.com/phsmith/rundeck_exporter?tab=readme-ov-file#api-authentication

Great, thank you will do!

**Comment by phsmith** [comment]
Hey @mbaleey, I just released version 2.8.0 of the exporter with a fix to properly throw the permission issue message.
I'm closing this issue, but feel free to open a new one if you're still having problems.
